apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: sample-spring-boot-app-openshiftawefwqer
build:
  artifacts:
    - image: granatengeorg-de/sample-spring-boot-app-openshiftawefwqer
      jib:
        args:
          - -Pjib
          - -DskipTests
manifests:
  rawYaml:
    - k8s/deployment.yaml
deploy:
  kubectl: {}